### ISSUE TITLE
Support using environment variables in configuration files

### ISSUE THREAD

**Issue by forman** [bcdev/zappend#36]
When loading configurations from JSON or YAML files, it should be possible to reference environment variables and insert their current values, for example

```json
{
  "slice_storage_options": {
    "key": "${CREODIAS_S3_KEY}",
    "secret": "${CREODIAS_S3_SECRET}"
   }
}
```

Or using YAML

```yaml
slice_storage_options:
  key: ${CREODIAS_S3_KEY}
  secret: ${CREODIAS_S3_SECRET}
```
